# Generated by Django 4.2.1 on 2024-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'User'), ('2', 'Operator'), ('3', 'Courier'), ('4', 'Manager')], default='1', max_length=255),
        ),
    ]
